blueprint:
  id: "b8449c4605574e309e1c5ed35c35c49d"
  name: "Hello World"
  description: "Simple Blueprint to create a cloud server"
  version: 1.0.0
  services:
    lb:
      component:
        interface: http
        type: load-balancer
        constraints:
        - algorithm: ROUND_ROBIN
      relations:
      - server: http
      display-name: Load Balancer
    "server":
      constraints:
      - setting: count
        greater-than-or-equal-to: 1
        less-than: 4
      - count: 1
      component:
        type: compute
        constraints:
          - os: Windows Server 2012 R2
          - flavor: performance1-2
        name: hw_instance
  options:
    region:
      type: string
      default: LON
      constrains:
        - resource_type: load-balancer
          service: lb
          setting: region
        - resource_type: compute
          service: "server"
          setting: region
environment:
  id: rackspace-open-cloud
  name: Rackspace Open Cloud
  providers:
    script:
      vendor: core
      constraints:
      - timeout: 1200
      catalog:
        application:
          hw_instance:
            provides:
            - application: http
            requires:
            - host: windows
            properties:
              scripts:
                install:
                  name: install.ps1
                  template: |
                    Get-Process | Out-File C:\Cloud-Automation\procs.txt
    load-balancer: {}
    nova: {}
    common:
      vendor: rackspace
